apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: hooky
build:
  artifacts:
  - image: hooky
    kaniko:
      image: gcr.io/kaniko-project/executor:debug-v0.11.0
      cache:
        repo: 'lazybit.ch/hooky/cache'
  cluster:
    namespace: jx
    dockerConfig:
      path: ~/.docker/config.json
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - image: hooky
      docker:
        network: host
        cacheFrom:
        - 'python:3.8-slim'
        noCache: false
    local:
      push: false
      useBuildkit: true
    tagPolicy:
      gitCommit: {}
