{{- if not .Values.slack.existingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hooky.fullname" . }}
  labels:
    {{- include "hooky.labels" . | nindent 4 }}
type: Opaque
stringData:
  SLACK_SIGNING_SECRET: {{ include "hooky.slackSigningSecret" . | quote }}
  SLACK_API_TOKEN: {{  .Values.slack.apiToken | quote }}
{{- end }}
