{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hooky.serviceAccountName" . }}
  labels:
{{ include "hooky.labels" . | nindent 4 }}
{{- end -}}
